modified:   setup.py
Changed line 20 in setup.py from "opencv-python>=3." to
"opencv-python>=3.0". This issue caused an error when
installing on Linux/WSL using "pip install -e .". But this bug is not
shown when install on macOS and Windows. The bug show:
Obtaining file:///mnt/e/Projects/gym
  Preparing metadata (setup.py) ... error
    error: subprocess-exited-with-error

        × python setup.py egg_info did not run successfully.
	  │ exit code: 1
	    ╰─> [1 lines of output]
	          error in gym setup command: 'extras_require' must be a
		  dictionary whose values are strings or lists of
		  strings containing valid project/version requirement
		  specifiers.
		        [end of output]

			    note: This error originates from a
			    subprocess, and is likely not a problem with
			    pip.
			    error: metadata-generation-failed

			    × Encountered error while generating package
			    metadata.
			    ╰─> See above for output.

			    note: This is an issue with the package
			    mentioned above, not pip.
			    hint: See above for details.