replace self.spec by getattr(self, 'spec', None) in core Env object
Accessing missing object attribute raises an exception that's not catched. For example

Traceback (most recent call last):
  File "policy_evaluation.py", line 5, in <module>
    print(env)
  File "/Users/QV/code-project/learn/sutton/venv/lib/python3.5/site-packages/gym/core.py", line 205, in __str__
    if self.spec is not None:
AttributeError: 'BlackjackEnv' object has no attribute 'spec'